export const SUPPORTED_SCHEMA_VERSIONS = ['v1'];
export const DEFAULT_SCHEMA_VERSION = 'v1';
export const MIN_SCHEMA_VERSION = SUPPORTED_SCHEMA_VERSIONS[0];
export const MAX_SCHEMA_VERSION = SUPPORTED_SCHEMA_VERSIONS[SUPPORTED_SCHEMA_VERSIONS.length - 1];
